---
all:
  children:
    proxmox_hosts:
      hosts:
        proxmox2:
          ansible_host: 10.10.100.11
        oreki-pve-001:
          ansible_host: 10.10.100.12
        oreki-pve-002:
          ansible_host: 10.10.100.13
      vars:
        ansible_ssh_private_key_file: ~/.ssh/homelab_key
        ansible_user: root
    vms:
      hosts:
        oreki-docker-001:
          ansible_host: 10.10.10.10
        oreki-fs-001:
          ansible_host: 10.10.10.11
        oreki-monitoring-001:
          ansible_host: 10.10.10.12
      vars:
        ansible_user: cross
  vars:
    ansible_python_interpreter: /usr/bin/python3
