$ANSIBLE_VAULT;1.1;AES256
62383135623064373034363631633865626630386162383365643636646466326162376166376438
6262376664343336393330356361383838616364633635370a626231653963393439356561363761
65616663666164396533373763663633653937313661366463363534396266333231363034363562
3435356261613232650a313032343732376463656136386163343562393438353032386233353837
65636430383734623934386461333263633435656566306434356434303939626564333834363563
61636632346561393537366262656630666538616438376538323734666130393062303739323432
39643231303537613562326661393637623338326633386237323239373535393636393738633534
38656266396566346365623034623565383530326666303166336536656433396461363065353866
32623364646366613436396432623937366138343963386233396561383235386663323330376263
66343036333666383161303564313064393162376534656332323864333632386237363266623338
63643966626136316432313331363232333737343239616130666465353162373437333064333633
38613466663138623032
