services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}
    ports:
      - '7575:7575'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`dashboard.lab.oreki.io`)"
      - "traefik.http.routers.homarr.entrypoints=http"
      - "traefik.http.routers.homarr.middlewares=homarr-https-redirect"
      - "traefik.http.middlewares.homarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homarr-secure.rule=Host(`dashboard.lab.oreki.io`)"
      - "traefik.http.routers.homarr-secure.entrypoints=https"
      - "traefik.http.routers.homarr-secure.tls=true"
      - "traefik.http.routers.homarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
    networks:
      - proxy

networks:
  proxy:
    external: true

